-- MySQL Script generated by MySQL Workbench
-- Fri Oct 28 11:41:03 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`PF`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`PF` (
  `idPF` INT NOT NULL,
  PRIMARY KEY (`idPF`),
  UNIQUE INDEX `idPF_UNIQUE` (`idPF` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`PJ`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`PJ` (
  `CNPJ` INT NOT NULL,
  PRIMARY KEY (`CNPJ`),
  UNIQUE INDEX `CNPJ_UNIQUE` (`CNPJ` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Cliente` (
  `idCliente` INT NOT NULL,
  `Nome` VARCHAR(80) NOT NULL,
  `Endereco` VARCHAR(70) NOT NULL,
  `E-mail` VARCHAR(45) NOT NULL,
  `Telefone` VARCHAR(45) NOT NULL,
  `PF_idPF` INT NOT NULL,
  `PJ_CNPJ` INT NOT NULL,
  PRIMARY KEY (`idCliente`),
  INDEX `fk_Cliente_PF1_idx` (`PF_idPF` ASC) VISIBLE,
  INDEX `fk_Cliente_PJ1_idx` (`PJ_CNPJ` ASC) VISIBLE,
  CONSTRAINT `fk_Cliente_PF1`
    FOREIGN KEY (`PF_idPF`)
    REFERENCES `mydb`.`PF` (`idPF`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Cliente_PJ1`
    FOREIGN KEY (`PJ_CNPJ`)
    REFERENCES `mydb`.`PJ` (`CNPJ`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Metodo_Pagamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Metodo_Pagamento` (
  `idPagamento` INT NOT NULL,
  `Forma_Pamaneto` VARCHAR(15) NOT NULL,
  `Cliente_idCliente` INT NOT NULL,
  PRIMARY KEY (`idPagamento`, `Cliente_idCliente`),
  INDEX `fk_Metodo_Pagamento_Cliente1_idx` (`Cliente_idCliente` ASC) VISIBLE,
  CONSTRAINT `fk_Metodo_Pagamento_Cliente1`
    FOREIGN KEY (`Cliente_idCliente`)
    REFERENCES `mydb`.`Cliente` (`idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Transportadora`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Transportadora` (
  `idTransportadora` INT NOT NULL,
  `Nome` VARCHAR(60) NOT NULL,
  `Endereco` VARCHAR(70) NOT NULL,
  `E-mail` VARCHAR(55) NOT NULL,
  `Telefone` VARCHAR(12) NOT NULL,
  PRIMARY KEY (`idTransportadora`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Pedido` (
  `idPedido` INT NOT NULL,
  `Data` date NULL,
  `Descricao` VARCHAR(250) NULL,
  `Valor_Total` VARCHAR(45) NULL,
  `Cliente_idCliente` INT NOT NULL,
  `Frete` DECIMAL(5,3) NULL,
  `Metodo_Pagamento_idPagamento` INT NOT NULL,
  `Metodo_Pagamento_Cliente_idCliente` INT NOT NULL,
  `Transportadora_idTransportadora` INT NOT NULL,
  PRIMARY KEY (`idPedido`, `Cliente_idCliente`, `Metodo_Pagamento_idPagamento`, `Metodo_Pagamento_Cliente_idCliente`, `Transportadora_idTransportadora`),
  INDEX `fk_Pedido_Cliente1_idx` (`Cliente_idCliente` ASC) VISIBLE,
  INDEX `fk_Pedido_Metodo_Pagamento1_idx` (`Metodo_Pagamento_idPagamento` ASC, `Metodo_Pagamento_Cliente_idCliente` ASC) VISIBLE,
  INDEX `fk_Pedido_Transportadora1_idx` (`Transportadora_idTransportadora` ASC) VISIBLE,
  CONSTRAINT `fk_Pedido_Cliente1`
    FOREIGN KEY (`Cliente_idCliente`)
    REFERENCES `mydb`.`Cliente` (`idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Pedido_Metodo_Pagamento1`
    FOREIGN KEY (`Metodo_Pagamento_idPagamento` , `Metodo_Pagamento_Cliente_idCliente`)
    REFERENCES `mydb`.`Metodo_Pagamento` (`idPagamento` , `Cliente_idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Pedido_Transportadora1`
    FOREIGN KEY (`Transportadora_idTransportadora`)
    REFERENCES `mydb`.`Transportadora` (`idTransportadora`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Fornecedor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Fornecedor` (
  `idFornecedor` INT NOT NULL,
  `Nome` VARCHAR(60) NOT NULL,
  `Endereco` VARCHAR(70) NOT NULL,
  `Telefone` VARCHAR(12) NOT NULL,
  PRIMARY KEY (`idFornecedor`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Produto` (
  `idProduto` INT NOT NULL,
  `Preco` DECIMAL NOT NULL,
  `Nome` VARCHAR(45) NOT NULL,
  `Descricao` VARCHAR(45) NULL,
  `Marca` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idProduto`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Estoque`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Estoque` (
  `idEstoque` INT NOT NULL,
  `Disponibilidade` SMALLINT(5) NULL,
  `Endereco` VARCHAR(70) NULL,
  `Estoquecol` VARCHAR(45) NULL,
  PRIMARY KEY (`idEstoque`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Fornece`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Fornece` (
  `Fornecedor_idFornecedor` INT NOT NULL,
  `Produto_idProduto` INT NOT NULL,
  PRIMARY KEY (`Fornecedor_idFornecedor`, `Produto_idProduto`),
  INDEX `fk_Fornecedor_has_Produto_Produto1_idx` (`Produto_idProduto` ASC) VISIBLE,
  INDEX `fk_Fornecedor_has_Produto_Fornecedor_idx` (`Fornecedor_idFornecedor` ASC) VISIBLE,
  CONSTRAINT `fk_Fornecedor_has_Produto_Fornecedor`
    FOREIGN KEY (`Fornecedor_idFornecedor`)
    REFERENCES `mydb`.`Fornecedor` (`idFornecedor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Fornecedor_has_Produto_Produto1`
    FOREIGN KEY (`Produto_idProduto`)
    REFERENCES `mydb`.`Produto` (`idProduto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Produto_Estoque`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Produto_Estoque` (
  `Produto_idProduto` INT NOT NULL,
  `Estoque_Quantidade_Produto` INT NOT NULL,
  PRIMARY KEY (`Produto_idProduto`, `Estoque_Quantidade_Produto`),
  INDEX `fk_Produto_has_Estoque_Estoque1_idx` (`Estoque_Quantidade_Produto` ASC) VISIBLE,
  INDEX `fk_Produto_has_Estoque_Produto1_idx` (`Produto_idProduto` ASC) VISIBLE,
  CONSTRAINT `fk_Produto_has_Estoque_Produto1`
    FOREIGN KEY (`Produto_idProduto`)
    REFERENCES `mydb`.`Produto` (`idProduto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Produto_has_Estoque_Estoque1`
    FOREIGN KEY (`Estoque_Quantidade_Produto`)
    REFERENCES `mydb`.`Estoque` (`idEstoque`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Produto_Pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Produto_Pedido` (
  `Produto_idProduto` INT NOT NULL,
  `Pedido_idPedido` INT NOT NULL,
  PRIMARY KEY (`Produto_idProduto`, `Pedido_idPedido`),
  INDEX `fk_Produto_has_Pedido_Pedido1_idx` (`Pedido_idPedido` ASC) VISIBLE,
  INDEX `fk_Produto_has_Pedido_Produto1_idx` (`Produto_idProduto` ASC) VISIBLE,
  CONSTRAINT `fk_Produto_has_Pedido_Produto1`
    FOREIGN KEY (`Produto_idProduto`)
    REFERENCES `mydb`.`Produto` (`idProduto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Produto_has_Pedido_Pedido1`
    FOREIGN KEY (`Pedido_idPedido`)
    REFERENCES `mydb`.`Pedido` (`idPedido`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Entrega`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Entrega` (
  `Codigo_Rastreio` INT NOT NULL,
  `Status` VARCHAR(60) NOT NULL,
  `Data_Prevista` DATE NOT NULL,
  `Data_Entrega` DATE NULL,
  `Transportadora_idTransportadora` INT NOT NULL,
  `Cliente_idCliente` INT NOT NULL,
  PRIMARY KEY (`Codigo_Rastreio`, `Transportadora_idTransportadora`, `Cliente_idCliente`),
  INDEX `fk_Entrega_Transportadora1_idx` (`Transportadora_idTransportadora` ASC) VISIBLE,
  INDEX `fk_Entrega_Cliente1_idx` (`Cliente_idCliente` ASC) VISIBLE,
  CONSTRAINT `fk_Entrega_Transportadora1`
    FOREIGN KEY (`Transportadora_idTransportadora`)
    REFERENCES `mydb`.`Transportadora` (`idTransportadora`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Entrega_Cliente1`
    FOREIGN KEY (`Cliente_idCliente`)
    REFERENCES `mydb`.`Cliente` (`idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
