-- HOW TO CREATE ASSERTION IN DBMS 
-- THAT ARE COMPATIBLE WITH ASSERTIONS

-- ASSERTION CREATION EXAMPLE
CREATE 'ASSERTION' SALARY_CONSTRAINT
CHECK(NOT EXISTS ( SELECT *
		FROM EMPLOYEE E, EMPLOYEE M,
			DEPARTAMENT D
		WHERE E.SALARY > M.SALARY
        AND E.DNO = D.DNUMBER
        AND D.MRG_SSN = M.SSN ));
        
