CALL sp_name([parameter[...]]);
CALL sp_name[()];

-- SIMPLE EXAMPLE OF RPOCEDURE
CREATE PROCEDURE p (OUT ver_param VARCHAR(25), INOUT incr_param INT)
BEGIN 
	# SET VALUE OF OU PARAMETER
    SELECT VERSION () INTO ver_param;
    # iNCREMENT VALUE OF INOUT PARAMENTER
    SET incr_param = incr_param + 1;
END;

-- ILUSTRATIVE EXAMPLE USING USER VARIABLES.
SET @increment = 10;
CALL p(@version,@increment);
SELECT @version, @increment;

-- ANOTHER PROCEDURE EXAMPLE
CREATE PROCEDURE do_repeat(p1 INT)
BEGIN 
		SET @x = 0;
		REPEAT 
			SET @x = @x + 1; 
			UNTIL @x > p1 END
		REPEAT;
END;

-- SQL FUNCTION EXAMPLE
-- WE CAN HAVE AN ALTER FUNCTION, THAT MEANS THAT WE CAN MANIPULE 
-- A FUNCTION BY A DDL
-- ILLUSTRATIVE EXAMPLE

ALTER FUNCTION func_name [characteristic...]
characteristic:{
	COMMENT 'STRING'
    |LANGUAGE SQL
	|{CONTAINS SQL|NO SQL|READS SQL DATA| MODIFIES SQL DATA}
	|SQL SECURITY {DEFINER|INVOKER}
}

-- FIRST FUNCTION EXAMPLE
CREATE FUNCTION HELLO (s CHAR(20))
RETURNS CHAR(50) DETERMINISTIC
RETURN CONCAT('Hello ',s,'!');
SELECT HELLO('World') AS FIRST_FUNCTION;



